### ISSUE TITLE
mod_label still mentioned at many places

### ISSUE THREAD

**Issue by mudrd8mz** [emeneo/description#3]
Please clean up the code and remove the traces to the original mod_label code that was used as a template for this module. Search for "label" to see them all.
When dealing with the `@copyright` tag, see the section 'Copyrights' at https://docs.moodle.org/dev/Plugin_contribution_checklist
In this case, you could just note in the README and in the description at moodle.org/plugins that your module is based on the Label module code, and have yourself everywhere in the `@copyright` tags.

**Comment by Flottertotte** [comment]
Have done a complete re-make.
