### ISSUE TITLE
The static folder

### ISSUE THREAD

**Issue by mudrd8mz** [emeneo/description#8]
There are multiple issues with it:
- Activity modules have in-built support for their CSS files, performing better than your `<script>` hackery. See https://docs.moodle.org/dev/CSS_coding_style
- There is no jquery.min.js in that folder that you try to load in mod_form. Even if you wanted jQuery, there are better ways to get it: https://docs.moodle.org/dev/jQuery

**Comment by Flottertotte** [comment]
fixed!
