### ISSUE TITLE
Get rid of files that are not actually used

### ISSUE THREAD

**Issue by mudrd8mz** [emeneo/description#9]
Files like `settings.php` or `db/upgrade.php` do not do anything at the moment. They just slow things down, consume memory etc. Better to avoid having them.

**Comment by Flottertotte** [comment]
I would prefer keeping them so that I do not forget they exist in case me or another developer needs them later on. They are very small and I think they only consume some kb of webspace...
Please let me know if I miss something.

**Comment by mudrd8mz** [comment]
Yeah, I can understand such reasoning. It is just my preference to keep the code doing and containing exactly what it needs - no more, no less. If every plugin in Moodle contained a template for every supported file / library, the lost performance would be significant I guess. Anyway, feel free to close, up to you really.
